### ISSUE TITLE
knife ec2 authentication failure

### ISSUE THREAD

**Issue by tfreundo** [tfreundo/LabCourse-group4-SS2016#1]
Connecting to ec2-52-29-162-184.eu-central-1.compute.amazonaws.com
DEBUG: Looking for bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/bootstrap/templates
DEBUG: Found bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/bootstrap/templates
DEBUG: Adding ec2-52-29-162-184.eu-central-1.compute.amazonaws.com
DEBUG: establishing connection to ec2-52-29-162-184.eu-central-1.compute.amazonaws.com:22
DEBUG: connection established
INFO: negotiating protocol version
DEBUG: remote is `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.4'
DEBUG: local is `SSH-2.0-Ruby/Net::SSH_3.0.2 x86_64-linux'
DEBUG: read 1648 bytes
DEBUG: received packet nr 0 type 20 len 1644
INFO: got KEXINIT from server
INFO: sending KEXINIT
DEBUG: queueing packet nr 0 type 20 len 1684
DEBUG: sent 1688 bytes
INFO: negotiating algorithms
DEBUG: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
DEBUG: exchanging keys
DEBUG: queueing packet nr 1 type 34 len 20
DEBUG: sent 24 bytes
DEBUG: read 152 bytes
DEBUG: received packet nr 1 type 31 len 148
DEBUG: queueing packet nr 2 type 32 len 140
DEBUG: sent 144 bytes
DEBUG: read 720 bytes
DEBUG: received packet nr 2 type 33 len 700
DEBUG: queueing packet nr 3 type 21 len 20
DEBUG: sent 24 bytes
DEBUG: received packet nr 3 type 21 len 12
DEBUG: beginning authentication of `ubuntu'
DEBUG: queueing packet nr 4 type 5 len 28
DEBUG: sent 52 bytes
DEBUG: read 52 bytes
DEBUG: received packet nr 4 type 6 len 28
DEBUG: trying none
DEBUG: queueing packet nr 5 type 50 len 44
DEBUG: sent 68 bytes
DEBUG: read 52 bytes
DEBUG: received packet nr 5 type 51 len 28
DEBUG: allowed methods: publickey
DEBUG: none failed
DEBUG: trying publickey
DEBUG: connecting to ssh-agent
DEBUG: sending agent request 1 len 44
DEBUG: received agent packet 2 len 5
DEBUG: sending agent request 11 len 0
DEBUG: received agent packet 12 len 5
ERROR: all authorization methods failed (tried none, publickey)
DEBUG: Looking for bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/bootstrap/templates
DEBUG: Found bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/bootstrap/templates
Failed to authenticate ubuntu - trying password auth
DEBUG: Looking for bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/bootstrap/templates
DEBUG: Found bootstrap template in /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/bootstrap/templates
Enter your password: 
DEBUG: Adding ec2-52-29-162-184.eu-central-1.compute.amazonaws.com
DEBUG: establishing connection to ec2-52-29-162-184.eu-central-1.compute.amazonaws.com:22
DEBUG: connection established
INFO: negotiating protocol version
DEBUG: remote is `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.4'
DEBUG: local is `SSH-2.0-Ruby/Net::SSH_3.0.2 x86_64-linux'
DEBUG: read 1648 bytes
DEBUG: received packet nr 0 type 20 len 1644
INFO: got KEXINIT from server
INFO: sending KEXINIT
DEBUG: queueing packet nr 0 type 20 len 1684
DEBUG: sent 1688 bytes
INFO: negotiating algorithms
DEBUG: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
DEBUG: exchanging keys
DEBUG: queueing packet nr 1 type 34 len 20
DEBUG: sent 24 bytes
DEBUG: read 152 bytes
DEBUG: received packet nr 1 type 31 len 148
DEBUG: queueing packet nr 2 type 32 len 140
DEBUG: sent 144 bytes
DEBUG: read 720 bytes
DEBUG: received packet nr 2 type 33 len 700
DEBUG: queueing packet nr 3 type 21 len 20
DEBUG: sent 24 bytes
DEBUG: received packet nr 3 type 21 len 12
DEBUG: beginning authentication of `ubuntu'
DEBUG: queueing packet nr 4 type 5 len 28
DEBUG: sent 52 bytes
DEBUG: read 52 bytes
DEBUG: received packet nr 4 type 6 len 28
DEBUG: trying none
DEBUG: queueing packet nr 5 type 50 len 44
DEBUG: sent 68 bytes
DEBUG: read 52 bytes
DEBUG: received packet nr 5 type 51 len 28
DEBUG: allowed methods: publickey
DEBUG: none failed
DEBUG: trying publickey
DEBUG: connecting to ssh-agent
DEBUG: sending agent request 1 len 44
DEBUG: received agent packet 2 len 5
DEBUG: sending agent request 11 len 0
DEBUG: received agent packet 12 len 5
ERROR: all authorization methods failed (tried none, publickey)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:194:in `rescue in new_session': Authentication failed for user ubuntu@ec2-52-29-162-184.eu-central-1.compute.amazonaws.com@ec2-52-29-162-184.eu-central-1.compute.amazonaws.com (Net::SSH::AuthenticationFailed)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:183:in `new_session'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'

**Comment by tfreundo** [comment]
- Be sure that the according .pem file is located at $HOME/.ssh (or add the file via `ssh-add privatekey.pem`
- Change file-permissions: `chmod 400 privatekey.pem`
- Check your knife.rb for the entry:
`knife[:identity_file] = "/home/username/.ssh/aws-seth.pem"`
